{
  config,
  pkgs,
  self,
  ...
}: let
  # https://blog.korfuri.fr/posts/2022/11/autogenerated-prometheus-configs-for-multiple-nixos-hosts/
  lib = pkgs.lib;
  # Find all the hosts who have a node_exporter enabled
  enabledNodeExportersF = hostName: host:
    lib.filterAttrs (k: v:
      if builtins.isAttrs v && k == "node"
      then v.enable == true
      else false)
    host.config.services.prometheus.exporters;

  # Build the scrape config for each enabled node_exporter
  mkScrapeConfigExporterF = hostname: ename: ecfg: {
    job_name = "${hostname}-${ename}";
    scrape_interval = "30s";
    static_configs = [{targets = ["${hostname}:${toString ecfg.port}"];}];
    relabel_configs = [
      {
        target_label = "instance";
        replacement = "${hostname}";
      }
      {
        target_label = "job";
        replacement = "${ename}";
      }
    ];
  };

  # From all the known hosts, fetch the enabled node_exporters
  enabledExporters = builtins.mapAttrs enabledNodeExportersF self.nixosConfigurations;

  # Build the scrape config for each host
  mkScrapeConfigHost = name: exporters:
    builtins.mapAttrs (mkScrapeConfigExporterF name) exporters;
  scrapeConfigsByHost = builtins.mapAttrs mkScrapeConfigHost enabledExporters;

  # Flatten the scrapeConfigsByHost into a list
  autogenScrapeConfigs = lib.flatten (map builtins.attrValues (builtins.attrValues scrapeConfigsByHost));
in {
  imports = [
    ./alert-manager.nix
  ];

  services.prometheus = {
    enable = true;
    port = 9001;
    extraFlags = [
      "--log.level=debug"
    ];
    checkConfig = "syntax-only";
    rules = [
      (builtins.readFile ./prometheus.rules.yaml)
    ];

    # Send to the local Alloy instance for forwarding to Grafana Cloud
    remoteWrite = [
      {
        name = "alloy";
        url = "http://localhost:9999/api/v1/metrics/write";
      }
    ];

    exporters = {
      blackbox = {
        enable = true;
        configFile = "${./blackbox.yml}";
      };
      smokeping = {
        enable = true;
        hosts = [
          "admin"
          "shelly-smokedetector"
          "shelly-codetecter"
          "192.168.20.105"
          "75.166.123.123"
          "1.1.1.1"
          "8.8.8.8"
        ];
      };
      # unpoller = {
      #   enable = true;
      # };
    };

    alertmanagers = [
      {
        scheme = "http";
        static_configs = [
          {
            targets = [
              "127.0.0.1:${toString config.services.prometheus.alertmanager.port}"
            ];
          }
        ];
      }
    ];

    scrapeConfigs =
      [
        {
          job_name = "unpoller";
          static_configs = [
            {
              targets = ["localhost:${toString config.services.prometheus.exporters.unpoller.port}"];
            }
          ];
        }
        {
          job_name = "smokeping";
          static_configs = [
            {
              targets = ["localhost:${toString config.services.prometheus.exporters.smokeping.port}"];
            }
          ];
        }
        {
          job_name = "condo-ha";
          honor_timestamps = true;
          scrape_interval = "30s";
          scrape_timeout = "10s";
          metrics_path = "/api/prometheus";
          scheme = "http";
          bearer_token_file = config.age.secrets.condo-ha-token.path;
          static_configs = [
            {
              targets = ["condo-ha:8123"];
            }
          ];
        }
        {
          job_name = "homeassistant";
          honor_timestamps = true;
          scrape_interval = "30s";
          scrape_timeout = "10s";
          metrics_path = "/api/prometheus";
          scheme = "http";
          bearer_token_file = config.age.secrets.homeassistant-token.path;
          static_configs = [
            {
              targets = ["homeassistant:8123"];
            }
          ];
        }
        {
          job_name = "blackbox_http";
          metrics_path = "/probe";
          params = {
            module = ["http_2xx"];
          };
          static_configs = [
            {
              targets = [
                "books"
                "photos"
              ];
            }
          ];
          relabel_configs = [
            {
              source_labels = ["__address__"];
              target_label = "__param_target";
              replacement = "http://$1";
            }
            {
              source_labels = ["__address__"];
              regex = "^([^/]+)(/.*)?";
              target_label = "instance";
            }
            {
              target_label = "__address__";
              replacement = "127.0.0.1:9115";
            }
          ];
        }
        {
          job_name = "homeassistant_node";
          scrape_interval = "30s";
          static_configs = [
            {
              targets = ["homeassistant:9100"];
            }
          ];
          relabel_configs = [
            {
              target_label = "instance";
              replacement = "homeassistant";
            }
            {
              target_label = "job";
              replacement = "node";
            }
          ];
        }
        {
          job_name = "condo_ha_node";
          scrape_interval = "30s";
          static_configs = [
            {
              targets = ["condo-ha:9100"];
            }
          ];
          relabel_configs = [
            {
              target_label = "instance";
              replacement = "condo-ha";
            }
            {
              target_label = "job";
              replacement = "node";
            }
          ];
        }
      ]
      ++ autogenScrapeConfigs;
  };
}
