#!/usr/bin/env bash

# tmux set-hook -g session-created 'run-shell "<this script> start #{hook_session_name}"'
# tmux set-hook -g session-closed 'run-shell "<this script> stop #{hook_session_name}"'


if [ $# -ne 2 ]; then
    echo "Usage: $0 [start|stop] <session_name>"
    exit 1
fi
SESSION_NAME=$2
CLEANED_SESSION_NAME=$(echo $SESSION_NAME | tr -cd '[:alnum:]')
KUBECONFIG_PATH=~/.kube/config-${CLEANED_SESSION_NAME}

case "$1" in
    start)
        cp ~/.kube/config $KUBECONFIG_PATH
        tmux setenv -t ${SESSION_NAME} KUBECONFIG $KUBECONFIG_PATH
        ;;
    stop)
        if [ -f $KUBECONFIG_PATH ]; then
            rm $KUBECONFIG_PATH
        fi
        ;;
    *)
        echo "Invalid argument. Usage: $0 [start|stop]"
        exit 1
        ;;
esac
