# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # https://discourse.nixos.org/t/correct-way-to-use-lm-sensors-in-nixos/10139
  # Generated by sensors-detect on Wed Jan  3 07:31:29 2024
  # This file is sourced by /etc/init.d/lm_sensors and defines the modules to
  # be loaded/unloaded.
  #
  # The format of this file is a shell script that simply defines variables:
  # HWMON_MODULES for hardware monitoring driver modules, and optionally
  # BUS_MODULES for any required bus driver module (for example for I2C or SPI).

  # HWMON_MODULES="coretemp nct6683"

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/605c5f34-5c20-4b2d-949e-6bd433384cca";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E414-177B";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/0281b6a0-e08c-4eef-997c-f6b2af675f18";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
